Add content to kubeconfig action result
canonical/charm-microk8s pull request #79
Opened 2023-05-25 06:49 UTC by hemanthnakkina

Add the content of kubeconfig to kubeconfig action result with key content. To keep compatability
with the previous versions, writing config file
onto the filesystem is not removed.
Change the config file path to $HOME/config with
$HOME defaults to /home/ubuntu.

2023-05-25 07:41 UTC, hemanthnakkina commented
Some more context on the fix: https://bugs.launchpad.net/snap-openstack/+bug/2019552

2023-05-25 16:47 UTC, neoaggelos requested changes
LGTM in general, one minor change and we can merge this

2023-05-26 00:53 UTC, hemanthnakkina commented on src/microk8scluster.py
> +        event.set_results({"kubeconfig": config_path, "content": yaml.dump(kubeconfig)})
Fixed, thanks for the review

2023-05-26 05:25 UTC, neoaggelos approved these changes

2023-05-26 05:25 UTC, merged